### ISSUE TITLE
Run button starts in the first project directory in the tree, not in the directory of the selected project

### ISSUE THREAD

**Issue by zatherz** [rameshvarun/love-ide#12]
I tested this after failures to start Love. I used a script that made a GUI dialog with the working directory from where it's started from (zenity --title "test" --info --text="$PWD").

**Comment by rameshvarun** [comment]
This is true - in fact, this is what I'm doing at https://github.com/rameshvarun/love-ide/blob/master/lib/main.js#L46. I did this since most people only use one project directory.

In the case of multiple project directories, I'm unsure what the proper behavior should be. One possibility is that we can scan the directories, looking for the first directory with a main.lua. Alternatively, we could try to get the directory of the currently active editor view (is this what you mean by 'selected project'?). I'm not sure which of these is more intuitive.

**Comment by zatherz** [comment]
I think what you could do is just get the directory of the current open file, then check if there exists a main.lua in it. If there does, run LOVE. If not, then print an error.

**Comment by rameshvarun** [comment]
Sorry for the ridiculous delay - was busy with school and I ended up forgetting about this.

I've fixed this issue in c5b52559023da17c3506af03397010e8a9fa109e, and it's pushed out in the latest version.

**Comment by zatherz** [comment]
Nice, thank you.
