### ISSUE TITLE
Shortcut to run the app

### ISSUE THREAD

**Issue by maluramichael** [rameshvarun/love-ide#19]
Is it possible to create a shortcut so i don't have to press the toolbar icon?

**Comment by rameshvarun** [comment]
I've added a command under the `atom-text-editor` scope called `love-ide:run-love`. This can be used to trigger the same run logic as the icon. You can bind this to a key in your user keymap (Atom > Keymap).

**Comment by anthony-viglione** [comment]
Since I am new to Lua, LOVE, and Atom, I didn't understand any of this. I found that, on Windows, you can go open Atom and then at the top go to Packages > Settings View > Key Bindings then click on where it says "your keymap file" in blue. This will open a new tab in Atom named keymap.cson with an explanation of how to use it. I wanted to use alt-r, so I placed the following below the text: 

'atom-text-editor':
    'alt-r' : 'love-ide:run-love'
    
Then I saved it and was able to run my main.lua file by pressing alt-r instead of having to click the button. Whatever key or combination would just go between the single quotes and replace alt-r.

Long message for a simple answer, but it took me like half an hour to figure it out so I thought I'd put my explanation in case anyone else like me came along.
