### ISSUE TITLE
Make the autocomplete functionality available as a separate package

### ISSUE THREAD

**Issue by tesselode** [rameshvarun/love-ide#9]
The autocomplete in this package is a lot nicer than in love-atom, and I think it would be nice to be able to install it without installing everything else that comes with love-ide. I don't know if this is the right place for a request like this, but I just wanted to throw that out there.

Edit: now that I think about it, I want some of the other functionality too, I just wish it wasn't all a package deal. My current solution is to modify the package info to remove the dependencies, but that's kind of janky. I'm not sure what I want tbh.....

**Comment by rameshvarun** [comment]
That's a good point - I think it's worth creating separate `autocomplete-love` and `hyperclick-love` packages. Then, love-ide can become a meta-package - this is the approach that [Ionide](https://github.com/ionide/ionide-installer) and [Nuclide](https://github.com/facebooknuclideapm/nuclide-installer) take. I'll start to do this, though I'll probably leave in the toolbar code, since It doesn't seem like it deserves it's own package.

For now, it should be possible to disable any package in Atom from the settings and have the other love-ide features work (e.g. if you disable hyperclick and tool-bar, the autocomplete will still work).

**Comment by rameshvarun** [comment]
Actually, it seems like it could be annoying to maintain multiple packages that share things like data files. Would a combination of adding an option to disable the installer, and the ability to disable packages work?

**Comment by tesselode** [comment]
I feel like it would be good enough to just remove the dependencies. That way people can get the components they want by installing the right packages. But then you do lose some convenience of having everything installed at once.

**Comment by rameshvarun** [comment]
Refactored out `autocomplete-love` and `hyperclick-love` in 2553198b64d4ce95104afe1ed8dff4299c9a05f2. The tool-bar provider is still in, but I have a better idea on how to handle that - I'll refactor that out as soon as I get that working.

**Comment by tesselode** [comment]
Awesome, thanks!
